<a href="https://colab.research.google.com/github/tanu-1906/data_science_lab_1/blob/main/MatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Determinant

In [1]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("The 3x3 matrix is:")
print(matrix)

The 3x3 matrix is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"\nThe determinant of the matrix is: {determinant}")


The determinant of the matrix is: 0.0


#Inverse matrix

In [6]:
import numpy as np

# Create a new, invertible 3x3 square matrix
invertible_matrix = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

print("The new invertible 3x3 matrix is:")
print(invertible_matrix)

# Compute the determinant of the new matrix to confirm it's not zero
new_determinant = np.linalg.det(invertible_matrix)
print(f"\nThe determinant of the new matrix is: {new_determinant}")

The new invertible 3x3 matrix is:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

The determinant of the new matrix is: 0.9999999999999964


In [9]:
# Compute the inverse of the new matrix
inverse_matrix = np.linalg.inv(invertible_matrix)

print("\nThe inverse of the new matrix is:")
print(inverse_matrix)


The inverse of the new matrix is:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [16]:
# Verify the inverse: A * A_inv should be close to the identity matrix
identity_check = np.dot(invertible_matrix, inverse_matrix)
print("\nVerification (A * A_inv should be close to identity matrix):")
print(identity_check)


Verification (A * A_inv should be close to identity matrix):
[[ 1.00000000e+00 -2.66453526e-15  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -7.10542736e-15  1.00000000e+00]]


# Linear Equations

In [11]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constant vector B
B = np.array([10, 20])

print("Coefficient matrix A:")
print(A)
print("\nConstant vector B:")
print(B)

Coefficient matrix A:
[[2 3]
 [4 5]]

Constant vector B:
[10 20]


In [15]:
# Solve the system of linear equations Ax = B
solution = np.linalg.solve(A, B)

print("\nSolution (x, y):")
print(solution)


Solution (x, y):
[5. 0.]


In [14]:
# Verify the solution by plugging values back into the original equations
# For equation 1: 2x + 3y
check1 = 2 * solution[0] + 3 * solution[1]
# For equation 2: 4x + 5y
check2 = 4 * solution[0] + 5 * solution[1]

print(f"\nVerification:")
print(f"2x + 3y = {check1} (expected 10)")
print(f"4x + 5y = {check2} (expected 20)")


Verification:
2x + 3y = 10.0 (expected 10)
4x + 5y = 20.0 (expected 20)
